# Generated by Django 6.0.2 on 2026-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='proof',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
